src/Isen.DotNet.Web/Models/ErrorViewModel.cs
using System;

namespace Isen.DotNet.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Isen.DotNet.Web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Isen.DotNet.Library.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Isen.DotNet.Web.Controllers
{
    public abstract class BaseController<T, TRepo> : Controller
        where T : BaseModel<T>
        where TRepo : IBaseRepository<T>
    {
        #region Membres et constructeur

        protected readonly TRepo Repository;

        protected BaseController(TRepo repository)
        {
            Repository = repository;
        }

        #endregion

        #region Actions MVC

        public virtual IActionResult Index() => View(Repository.GetAll());

        [HttpGet] // facultatif car par défaut
        public virtual IActionResult Edit(int? id)
        {
            if (id == null) return View();
            return View(Repository.Single(id.Value));
        }

        [HttpPost]
        public virtual IActionResult Edit(int id, [Bind] T model)
        {
            Repository.Update(model);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public virtual IActionResult Delete(int? id)
        {
            if (id != null)
            {
                Repository.Delete(id.Value);
                Repository.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        #endregion

        #region API

        [HttpGet]
        [Route("api/[controller]/status")]
        public virtual JsonResult Status()
        {
            dynamic result = new ExpandoObject();
            result.serverTime = DateTime.Now;
            result.controller = typeof(T).Name;
            return Json(result);
        }

        [HttpGet]
        [Route("api/[controller]/{id}")]
        public virtual JsonResult GetById(int id)
        {
            var entity = Repository.Single(id);
            if (entity == null) return Json(new {});
            return Json(entity.ToDynamic());
        }

        [HttpGet]
        [Route("api/[controller]")]
        public virtual string GetAll()
        {
            var all = Repository
                .GetAll()
                .Select(e => e.ToDynamic())
                .ToList();
            return JsonConvert.SerializeObject(all, Formatting.Indented);
        }

        #endregion
    }
}

src/Isen.DotNet.Web/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Isen.DotNet.Library.Models;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;

namespace Isen.DotNet.Web.Controllers
{
    public class ClubController : BaseController<Club, IClubRepository>
    {
        public ClubController(IClubRepository repository) : base(repository)
        {
        }
    }
}

src/Isen.DotNet.Web/Controllers/HistoriqueController.cs
using Isen.DotNet.Library.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Isen.DotNet.Web.Controllers
{
    public class HistoriqueController : BaseController<Historique, IHistoriqueRepository>
    {
        public HistoriqueController(IHistoriqueRepository repository) : base(repository)
        {
        }
    }
}

src/Isen.DotNet.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;

namespace Isen.DotNet.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Isen.DotNet.Web/Controllers/JoueurController.cs
using Isen.DotNet.Library.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Isen.DotNet.Web.Controllers
{
    public class JoueurController : BaseController<Joueur, IJoueurRepository>
    {
        public JoueurController(IJoueurRepository repository) : base(repository)
        {
        }
    }
}

src/Isen.DotNet.Web/Views/Club/Edit.cshtml
@{
    ViewData["Title"] = "Edition d'un club'";
}
@using Isen.DotNet.Library.Models
@model Club
<h1>Edition d'un club' (formulaire)</h1>

<div class="row">
    <div class="col-12">
        
        <form class="form-group" asp-action="Edit">
            
            <input type="hidden" 
                   asp-for="Id"
                   value="@Model?.Id" />

            <div class="form-group">
                <label for="clubName">Nom du club</label>
                <input id="clubName"
                       type="text"
                       class="form-control"
                       placeholder="Club name"
                       asp-for="Name"
                       value="@Model?.Name" />
            </div>
            
            <div class="form-group">
                <label for="clubAdresse">Adresse</label>
                <input id="clubAdresse"
                       type="text"
                       class="form-control"
                       placeholder="Adresse"
                       asp-for="Adresse"
                       value="@Model?.Adresse" />
            </div>

            <div class="form-group">
                <label for="clubGPS">GPS</label>
                <input id="clubGPS"
                       type="text"
                       class="form-control"
                       placeholder="GPS"
                       asp-for="GPS"
                       value="@Model?.GPS" />
            </div>

            <div class="form-group">
                <label for="clubLogo">Logo URL</label>
                <input id="clubLogo"
                       type="text"
                       class="form-control"
                       placeholder="Logo"
                       asp-for="Logo"
                       value="@Model?.Logo" />
            </div>

            <button type="submit" class="btn btn-primary">Valider</button>
            <a class="btn btn-secondary"
               asp-controller="Club" asp-action="Index">Annuler</a>

        </form>

    </div>
</div>

src/Isen.DotNet.Web/Views/Club/Index.cshtml
@{
    ViewData["Title"] = "Tous les clubs";
}
@using Isen.DotNet.Library.Models
@model IEnumerable<Club>

<h1>Tous les clubs</h1>

<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Id</th>
          <th scope="col">Nom</th>
          <th scope="col">Adresse</th>
          <th scope="col">GPS</th>
          <th scope="col">Logo</th>
          <th>Action...</th>
      </tr>
  </thead>
  <tbody>
    @foreach(var club in Model)
    { 
      <tr>
          <th scope="row">@club.Id</th>
          <td>@club.Name</td>
          <td>@club.Adresse</td>
          <td>@club.GPS</td>
          <td><img src=@club.Logo width="50" length ="50"></td>
          <td>
              <a class="btn btn-outline-primary"
                 asp-controller="Club"
                 asp-action="Edit"
                 asp-route-id="@club.Id">Modifier</a>
              <a class="btn btn-outline-danger"
                 asp-controller="Club"
                 asp-action="Delete"
                 asp-route-id="@club.Id">Supprimer</a>
          </td>
      </tr>
     }
  </tbody>
</table>

src/Isen.DotNet.Web/Views/Historique/Edit.cshtml
@{
    ViewData["Title"] = "Edition d'un Historique'";
}
@using Isen.DotNet.Library.Models
@using Isen.DotNet.Library.Repositories.Interfaces
@model Historique
@inject IClubRepository _clubRepository
@inject IJoueurRepository _joueurRepository
<h1>Edition d'un Historique' (formulaire)</h1>

<div class="row">
    <div class="col-12">
        
        <form class="form-group" asp-action="Edit">
            
            <input type="hidden" 
                   asp-for="Id"
                   value="@Model?.Id" />

            
            <div class="form-group">
                <label for="Joueuse">Joueuse</label>
                @Html.DropDownListFor(
                    h => h.JoueurId,
                    new SelectList(
                        _joueurRepository.GetAll(),
                        "Id",
                        "Name"),
                    "Sélectionnez une joueuse...",
                    new { @class = "form-control" }
                    )
            </div>

            <div class="form-group">
                <label for="Club">Club</label>
                @Html.DropDownListFor(
                    h => h.ClubId,
                    new SelectList(
                        _clubRepository.GetAll(),
                        "Id",
                        "Name"),
                    "Sélectionnez un club...",
                    new { @class = "form-control" }
                    )
            </div>


            <div class="form-group">
                <label for="situation">Situation du club</label>
                <input id="clubName"
                       type="text"
                       class="form-control"
                       placeholder="Situation"
                       asp-for="Name"
                       value="@Model?.Name" />
            </div>

            <div class="form-group">
                <label for="Debut">Date de Début</label>
                <input id="Debut"
                       type="text"
                       class="form-control"
                       asp-for="Debut"
                       value="@Model?.Debut.ToShortDateString()"/>
            </div>

            <div class="form-group">
                <label for="Fin">Date de Fin</label>
                <input id="Fin"
                       type="text"
                       class="form-control"
                       asp-for="Fin"
                       value="@Model?.Fin.ToShortDateString()" />
            </div>
            

            <button type="submit" class="btn btn-primary">Valider</button>
            <a class="btn btn-secondary"
               asp-controller="Club" asp-action="Index">Annuler</a>

        </form>

    </div>
</div>

src/Isen.DotNet.Web/Views/Historique/Index.cshtml
@{
    ViewData["Title"] = "Tous les Historiques";
}
@using Isen.DotNet.Library.Models
@model IEnumerable<Historique>

<h1>Tous les Historique</h1>

<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Id</th>
          <th scope="col">Joueur</th>
          <th scope="col">Nom du club</th>
          <th scope="col">Situation du club</th>
          <th scope="col">Date de début</th>
          <th scope="col">Date de fin</th>
          <th>Action...</th>
      </tr>
  </thead>
  <tbody>
    @foreach(var historique in Model)
    { 
      <tr>
          <th scope="row">@historique.Id</th>
          <td>@historique.Joueur.Name</td>
          <td>@historique.Club.Name</td>
          <td>@historique.Name</td>
          <td>@historique.Debut.Date.ToString("d")</td>
          <td>@historique.Fin.Date.ToString("d")</td>

          <td>
              <a class="btn btn-outline-primary"
                 asp-controller="Historique"
                 asp-action="Edit"
                 asp-route-id="@historique.Id">Modifier</a>
              <a class="btn btn-outline-danger"
                 asp-controller="Historique"
                 asp-action="Delete"
                 asp-route-id="@historique.Id">Supprimer</a>
          </td>
      </tr>
     }
  </tbody>
</table>

src/Isen.DotNet.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Isen.DotNet.Web/Views/Joueur/Edit.cshtml
@{
    ViewData["Title"] = "Edition d'une ville";
}
@using Isen.DotNet.Library.Models
@using Isen.DotNet.Library.Repositories.Interfaces
@model Joueur
@inject IClubRepository _clubRepository
<h1>Edition d'une joueuse'e</h1>

<div class="row">
    <div class="col-12">
        
        <form class="form-group" asp-action="Edit">

            <input type="hidden"
                   asp-for="Id"
                   value="@Model?.Id" />

            <div class="form-group">
                <label for="LastName">Nom</label>
                <input id="LastName"
                       type="text"
                       class="form-control"
                       placeholder="Last name"
                       asp-for="LastName"
                       value="@Model?.LastName" />
            </div>

            <div class="form-group">
                <label for="FirstName">Prénom</label>
                <input id="FirstName"
                       type="text"
                       class="form-control"
                       placeholder="First name"
                       asp-for="FirstName"
                       value="@Model?.FirstName" />
            </div>
            
            @{
                var dateString = Model?.DateOfBirth
                    .GetValueOrDefault(DateTime.MinValue)
                    .ToString("dd/MM/yyyy");
            }

            <div class="form-group">
                <label for="DateOfBirth">Date de naissance</label>
                <input id="DateOfBirth"
                       type="text"
                       class="form-control"
                       placeholder="Date de naissance"
                       asp-for="DateOfBirth"
                       value="@dateString" />
            </div>
            
            

            <button type="submit" class="btn btn-primary">Valider</button>
            <a class="btn btn-secondary"
               asp-controller="Joueur" asp-action="Index">Annuler</a>

        </form>

    </div>
</div>

src/Isen.DotNet.Web/Views/Joueur/Index.cshtml
@{
    ViewData["Title"] = "Toutes les Joueuses";
}
@using Isen.DotNet.Library.Models
@model IEnumerable<Joueur>

<h1>Toutes les joueuses</h1>

<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Id</th>
          <th scope="col">Nom</th>
          <th scope="col">Prénom</th>
          <th scope="col">Date de naissance</th>
          <th scope="col">Age</th>
          <th>Action...</th>
      </tr>
  </thead>
  <tbody>
    @foreach(var joueur in Model)
    { 
        var dateString = joueur.DateOfBirth.HasValue ?
            joueur.DateOfBirth.Value.ToShortDateString() :
            "";
      <tr>
          <th scope="row">@joueur.Id</th>
          <td>@joueur.LastName</td>
          <td>@joueur.FirstName</td>
          <td>@dateString</td>
          <td>@joueur.Age an(s)</td>
          <td>
              <a class="btn btn-outline-primary"
                 asp-controller="Joueur"
                 asp-action="Edit"
                 asp-route-id="@joueur.Id">Modifier</a>
              <a class="btn btn-outline-danger"
                 asp-controller="Joueur"
                 asp-action="Delete"
                 asp-route-id="@joueur.Id">Supprimer</a>
          </td>
      </tr>
     }
  </tbody>
</table>

src/Isen.DotNet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Isen.DotNet.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    Isen<strong>.Net 👍</strong>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                                asp-area="" 
                                asp-controller="Home" 
                                asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                                asp-area="" 
                                asp-controller="Home" 
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle"
                               data-toggle="dropdown"
                               href="#" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Clubs</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Club" 
                                   asp-action="Index">Toutes</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Club" 
                                   asp-route-id=""
                                   asp-action="Edit">Ajouter...</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle"
                               data-toggle="dropdown"
                               href="#" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Joueuses</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Joueur" 
                                   asp-action="Index">Toutes</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Joueur" 
                                   asp-route-id=""
                                   asp-action="Edit">Ajouter...</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle"
                               data-toggle="dropdown"
                               href="#" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Historiques</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Historique" 
                                   asp-action="Index">Toutes</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Historique" 
                                   asp-route-id=""
                                   asp-action="Edit">Ajouter...</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Isen.DotNet.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>